[modules]
    #[modules.keylight]
    #    names = ["Key Light Left", "Key Light Right"]
    [modules.motu]
        ip = "10.0.1.5"
        color = [255, 80, 0]
    #[modules.camera]
    #    name = "A:4BE2529F"
    #[modules.other]
    #    something = "I AM TYPING SOMETHING THIS IS A STRING"


##Defined Actions
[[action]]
    btn = 0
    module = "motu"
    action = "vol_up"
    desc = "VOL +"
    value = "volume"
    display = "volume"

[[action]]
    btn = 5
    module = "motu"
    action = "vol_down"
    desc = "VOL -"
    value = "volume"
    display = "volume"